### ISSUE TITLE
how it is better than menixator regex script? what is the difference?

### ISSUE THREAD

**Issue by Alex-Github-Account** [8LWXpg/RegExHotstring#1]
https://github.com/menixator/hotstring

To me, not having any key to be set as activator is a big drawback.

I did script that automatically replaces ';' (semicolon) to either =. -. *. or ! depending on context of entered text (js code) and using regex.
For this to work custom activators needed, so I end up with menixator regex script.

**Comment by 8LWXpg** [comment]
This script is actually inspired by that. The reasons I made a new one is because the old one is made before InputHook created, so it

**Comment by 8LWXpg** [comment]
This script is actually inspired by that. The reason I made a new one is because the old one is created before InputHook is created. I think is more efficient and easier to modify with InputHook.

I'm currently working on making the option for no end keys, maybe it'll out in two days.

_I miss clicked "close with comment" sorry for that_

**Comment by Alex-Github-Account** [comment]
well, with * it is very promising. actually menixator script have multiple problems so I gonna try yours now. That was a quick fix! 
Let me be the first who starred!
